### ISSUE TITLE
Add redirect_uri param to requests

### ISSUE THREAD

**Issue by zupolgec** [rootinc/laravel-azure-middleware#37]
I found out that this package has a bug: if multiple redirect URIs are configured on the app on Azure portal, the last one is used to redirect back.

`redirect_uri` param should be added to the azure url and the following requests. Adding that fixes this issue.

Should I go ahead and make a PR? Should we add the `redirect_uri` as a configurable param, or just refer to the "login/azurecallback" route (maybe transforming that into a named route)?

**Comment by danieltjewett** [comment]
Hi @zupolgec.  Yes, if there is a bug, let's submit a PR and we can take a look at pushing that through.  As far as your question, let us see the code and we can determine where to go from there.  Thanks!

**Comment by jimmypuckett** [comment]
@danieltjewett I have put up a PR for this.  Please let me know if you see anything that you would like me to change.

**Comment by danieltjewett** [comment]
@zupolgec @jimmypuckett I noted this in the linked PR, but I understand a bit more what this issue was asking for. We've always supplied the callback in the Azure portal. However, I can see wanting to supply a `redirect_uri`.  I proposed a few ideas  in the linked PR to account for both paradigms.  Thanks again for contributing!
