### ISSUE TITLE
Cors Issue

### ISSUE THREAD

**Issue by francis-fullstack** [rootinc/laravel-azure-middleware#50]
My trying to submit a post request, to add a user. Using Axios in my react app. But I'm Having a cors error

**Comment by danieltjewett** [comment]
I don't believe this package is the issue, but we need more information to investigate further.  If you're trying to POST to an API in the Azure App from another site, you will have to login to the Azure App using the normal Azure login methods.  I don't believe Azure has anyway to log the user in through APIs routes.

**Comment by francis-fullstack** [comment]
laravel api : https://prnt.sc/11v0ngp
reactjs submit post request to api:  https://prnt.sc/11v0stf

error message when submitting post: https://prnt.sc/11v0wgl

let me know your thoughts on this.

**Comment by danieltjewett** [comment]
1. I'd recommend https://github.com/fruitcake/laravel-cors for CORs.
2. This package uses the session to store the Azure tokens.  It's generally an anti-pattern to use session with an API route, but it is possible: https://stackoverflow.com/questions/59037485/how-to-get-sessions-working-in-laravel-api-routes. Otherwise, you're looking at passing some kind of token with the request from the `:3000` app to the `:8000` app that specifies who the user is -- separate of the Azure system.  This can be done by authenticating on the `:8000` app and then storing / passing the token after `success` handler.  Then, the `:3000` app could use that token to authenticate against the `:8000` app's API routes in a different middleware.

**Comment by francis-fullstack** [comment]
kernel.php: https://prnt.sc/11wh3kz

https://prnt.sc/11wh56n

can you check what's the problem here?

**Comment by francis-fullstack** [comment]
But when I removed the middleware azure in api.php, post request works.

**Comment by danieltjewett** [comment]
Is it possible to show the error message in detail coming back from the post request?

**Comment by francis-fullstack** [comment]
"no access-control-allow-origin' header is present on the requested resource. if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with cors disabled"

that's the error message

**Comment by danieltjewett** [comment]
I am still unsure how this package would effect a CORs issue.  As long as the session is set in the API, and your user is authenticated on the app with the API, this should work.  The only other thing I can think of is double checking middleware priority.  Perhaps since the key `azure` comes first alphabetically, maybe this eating the CORs middleware, giving the error that it is a CORs problem whenever the middleware is enabled?  https://laravel.com/docs/8.x/middleware#sorting-middleware
