### ISSUE TITLE
Auth::check() is still false

### ISSUE THREAD

**Issue by lxg95** [rootinc/laravel-azure-middleware#9]
Hello there,

First of all i have to say i am very new to Laravel, OAuth and Middleware and i am very unexperienced.
I am using the extended installation of this repository and i am able to get the access_token and get the user data from it and my page looks like authentication is working completely.
The problem is that Auth::check() is never true after i logged in on my Web-Application.
Now i am worrying that the access_token only provides me with data but isn't validated and my App is not secure.
Can you tell me how i make Auth::check() working on my page after the extended installation is installed? Do i have to do something else (like the callback on every handshake thing)?
I never did the "php artisan make:auth"-command! Should i do that?

I hope this is the right place to ask and i hope you can help me out with my problem :)

LG lxg

**Comment by danieltjewett** [comment]
No worries @lxg95 

Currently this package does not use Laravel Auth out-of-the-box.  In a current project however, we are making use of Laravel Auth, and I was literally thinking about ways of making this package integrate with Laravel Auth more seamlessly.

Anyway, since you are following along with the extended installation, replace

```
$request->session()->put('user_id', $user->id);
```

with

```
Auth::login($user, true);
```

And that should make all of Laravel's Auth packages work!

**Comment by lxg95** [comment]
nice, it's working! thank you so much!!
And what about my concern that the token is not validated?
The step "calls web api with access_token in Authorization_header" in "OAuth 2.0 Authorization Flow" one can see in this [uri ](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) is executed?

**Comment by danieltjewett** [comment]
Sorry, I must have missed that part.

When the first "handshake" is established, an `access_token` and `refresh_token` is generated from Microsoft.  We can assume since we just returned from Azure, the token is valid.

On future requests, we always authenticate (or revalidate) with the Azure server, by passing in the `refresh_token` here:
https://github.com/rootinc/laravel-azure-middleware/blob/master/src/Azure.php#L45

**Comment by lxg95** [comment]
ok i think i've got all i need for now
Thank you very much :)
